### ISSUE TITLE
writing permisson should include reading permission

### ISSUE THREAD

**Issue by ChristianStrotkoetter** [madnetdev/regmon-os#21]
If an athlete grants writing permissions for a form / notes for a trainer, this should include reading permission (view in calendar) for this form as well.
Additional info: If an athlete checks the write-box, the read-box is already checked automatically.

**Comment by madnetdev** [comment]
The problem comes from wrong assignment in installed data.
data was:
![2023-09-27 142309](https://github.com/madnetdev/regmon-os/assets/115354386/b7031afe-f2ae-458b-a93f-06c2262da654)
1. The 'Note_n' should always be the first item.
2. When we give write permission we also give the read permission. The app do that but you probable change that manually.


data should be:
![2023-09-27 142725](https://github.com/madnetdev/regmon-os/assets/115354386/7b9c1ff0-5f45-404e-a40e-a69c3c159305)

**Comment by ChristianStrotkoetter** [comment]
Ok, sounds good, thanks for the info.
