### ISSUE TITLE
How to read Apache error.log when using Docker?

### ISSUE THREAD

**Issue by madnetdev** [madnetdev/regmon-os#27]
Reading of Apache error.log is crucial when you developing with PHP.
How you guys read Apache error.log when using Docker?

**Comment by kencreek** [comment]
In a terminal type 

docker logs regmon-os-web-1

if your container is named as regmon-os-web-1. You can also open Docker Desktop and click on the container web-1 under regmon-os. In either case the containers must be running.

**Comment by madnetdev** [comment]
This `docker logs regmon_os-web-1` works but there are some problems. 
1. it returns all logs including the access.log
2. it returns all the file and is not something you can easy work with.

I am thinking something like a file bind to a local file if this is possible.

**Comment by kencreek** [comment]
If running on linux you can filter logs like

docker logs regmon-os-web-1 2>&1 | grep error 
or
docker logs container_name_or_id 2>&1 | grep -E "GET|POST|PUT|DELETE"

On windows something similar might exist but dunno. 

You could also filter the logs in a different way by using a log collection and aggregation solution like the ELK Stack (Elasticsearch, Logstash, Kibana) or Fluentd with Elasticsearch and Kibana to centralize and manage your logs. These tools can provide better log organization and searching capabilities.

You also could use bind mounts as you already said. 
Edit the docker-compose

volumes:
      - /path/to/local/access.log:/var/log/apache2/access.log   # binds the local access log file to the container's access log.
      - /path/to/local/error.log:/var/log/apache2/error.log   # binds the local error log file to the container's error log
      
But then you could run into issues because access.log and error.log is linked to the container's stdout (console). So you must modify the apache server and tell that there should be the error log file on one hand and the link do stdout on the other hand. But I haven't done this so far.

**Comment by madnetdev** [comment]
I used to have the error.log empty when developing, 
this way you can easy find out the new errors.
After I solve the error I empty again the error.log.

So I apply the "volumes" solution and it works like I need it to.
